### ISSUE TITLE
If Batch size is 2 or more, only the first heatmap is created

### ISSUE THREAD

**Issue by poko3347** [kousw/stable-diffusion-webui-daam#5]
Thanks for the useful extension. I'll use it right away and have a few requests I have a few requests.

If the Batch size is 2 or more, only the first heatmap is created.

If "Always save all generated images" is not enabled, the heatmap will not be displayed in the browser.

I would like to be able to use words that include attention. For example (cat:1.2).
This is useful when copying multiple words at once from a prompt.

**Comment by kousw** [comment]
Fixed.

**Comment by poko3347** [comment]
Thanks.
Words with attention are now recognized, but the heatmap does not seem to be generated correctly.
Also, the issue of heatmaps not being generated when "Always save all generated images" is disabled was not fixed.


![haehajajejaeje](https://user-images.githubusercontent.com/51774685/205492683-ba544ec0-7c4d-49f6-b4e5-dd4a34441a70.jpg)

**Comment by kousw** [comment]
The prompt emphasis in web ui is not actually recognized as a token. Use only the word "cat".

>"Always save all generated images"
The web ui extension mechanism is still poor, so it is implemented in a way that hooks into image generation.
It is possible to force it to be done. However, I do not want to do it at this time because it would be complicated to implement.

**Comment by poko3347** [comment]
OK, I understand.
I'll close the title bug now that it's fixed.
